from debian:latest

run apt-get update -qq && \
    apt-get --no-install-suggests --no-install-recommends -y install \
	bison autoconf autotools-dev automake libncurses5-dev \
	pkg-config build-essential libssl-dev libbsd-dev libtls-dev
